services:
  mysql:
    image: mysql:8.0.37
    volumes:
      - ./app:/app
      - ./mysql:/var/lib/mysql
    env_file:
      - .env
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "--user=root", "--password=${MYSQL_ROOT_PASSWORD}", "--host=127.0.0.1", "ping", "--silent"]
      interval: 2s
      timeout: 10s
      retries: 10
    command: ["--default-authentication-plugin=mysql_native_password"]
    restart: unless-stopped

  django:
    volumes:
      - ./app:/app
    env_file:
      - ./app/project/.env_production
    build:
      context: ./app
    ports:
      - "80:8000"
    depends_on:
      - mysql 
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 2021:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql


  lb:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # - /etc/letsencrypt/live/thek.ai/fullchain.pem:/etc/nginx/fullchain.pem:ro
      # - /etc/letsencrypt/live/thek.ai/privkey.pem:/etc/nginx/privkey.pem:ro

    depends_on:
      - django
    ports:
      - '83:80'
      # - '443:443'
    restart: unless-stopped 
